### ISSUE TITLE
Exposing a read stream for find?

### ISSUE THREAD

**Issue by domharrington** [serby/save#26]
Would be great to expose a way to return streams of data from `.find()`. Maybe using the same interface that mongodb uses: `var stream = collection.find().stream()`

Obviously this would need to be implemented in the memory-engine and then again in save-mongodb.

**Comment by serby** [comment]
This is possible in the mongo engine, but more work is required.

A write stream is needed on create also.

**Comment by serby** [comment]
This is related #27

**Comment by serby** [comment]
Added in 7e78675ee705946ae1fc3868884de6efca49351e
