### ISSUE TITLE
Cursor support

### ISSUE THREAD

**Issue by confuser** [serby/save#27]
Addition of a method that would allow engines to provide cursor (like) implementations.

Would require implementation within the engines themselves as well.

Example interface similar to async.each
save.findEach(query, function (obj, cb) { cb(null) }, callback)

**Comment by serby** [comment]
Cursors will be supported very soon, but they will implement the standard streaming interface. 

```
find({})
  .pipe(es.stringify())
  .pipe(process.stdout)
```

**Comment by serby** [comment]
This is now possible: https://github.com/serby/save-mongodb/blob/master/lib/mongodb-engine.js#L189-L219

Further work is needed to make save completely streamable
